definitions:
  config:
    /hippo:namespaces/exdocpickerbasedemo/newsdocument:
      jcr:primaryType: hipposysedit:templatetype
      jcr:mixinTypes: ['editor:editable', 'mix:referenceable']
      jcr:uuid: 8873a89e-676b-4c5d-aa0a-afcf3a7d2ded
      /hipposysedit:nodetype:
        jcr:primaryType: hippo:handle
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: 7a85b702-e39b-46b0-9759-a77d98c3e3c1
        /hipposysedit:nodetype:
          jcr:primaryType: hipposysedit:nodetype
          jcr:mixinTypes: ['hipposysedit:remodel', 'mix:referenceable']
          jcr:uuid: 0e7abe30-c9e9-459a-8d1e-c3d6cb02463c
          hipposysedit:node: true
          hipposysedit:supertype: ['exdocpickerbasedemo:basedocument', 'hippostd:relaxed',
            'hippotranslation:translated']
          hipposysedit:uri: http://www.onehippo.org/exdocpickerbasedemo/nt/1.0
          /title:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: exdocpickerbasedemo:title
            hipposysedit:primary: false
            hipposysedit:type: String
          /introduction:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: exdocpickerbasedemo:introduction
            hipposysedit:primary: false
            hipposysedit:type: Text
          /content:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: exdocpickerbasedemo:content
            hipposysedit:primary: false
            hipposysedit:type: hippostd:html
          /date:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: exdocpickerbasedemo:date
            hipposysedit:primary: false
            hipposysedit:type: Date
            hipposysedit:validators: [required]
          /image:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: exdocpickerbasedemo:image
            hipposysedit:primary: false
            hipposysedit:type: hippogallerypicker:imagelink
          /author:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: exdocpickerbasedemo:author
            hipposysedit:primary: false
            hipposysedit:type: String
          /source:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: exdocpickerbasedemo:source
            hipposysedit:primary: false
            hipposysedit:type: String
          /location:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: exdocpickerbasedemo:location
            hipposysedit:primary: false
            hipposysedit:type: String
      /hipposysedit:prototypes:
        jcr:primaryType: hipposysedit:prototypeset
        /hipposysedit:prototype:
          jcr:primaryType: exdocpickerbasedemo:newsdocument
          jcr:mixinTypes: ['mix:referenceable']
          jcr:uuid: 0d4f6651-ae26-4c7b-b931-388056e4b684
          exdocpickerbasedemo:date: 0001-01-01T13:00:00+01:00
          exdocpickerbasedemo:documenttype: news
          exdocpickerbasedemo:introduction: ''
          exdocpickerbasedemo:title: ''
          hippo:related___pathreference: []
          hippostd:holder: holder
          hippostd:state: draft
          hippostdpubwf:createdBy: ''
          hippostdpubwf:creationDate: 2013-09-16T18:03:51.692+02:00
          hippostdpubwf:lastModificationDate: 2013-09-16T18:03:51.691+02:00
          hippostdpubwf:lastModifiedBy: ''
          hippotranslation:id: document-type-locale-id
          hippotranslation:locale: document-type-locale
          /exdocpickerbasedemo:content:
            jcr:primaryType: hippostd:html
            hippostd:content: <html><body></body></html>
          /exdocpickerbasedemo:image:
            jcr:primaryType: hippogallerypicker:imagelink
            hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
            hippo:facets: []
            hippo:modes: []
            hippo:values: []
      /editor:templates:
        jcr:primaryType: editor:templateset
        /_default_:
          jcr:primaryType: frontend:plugincluster
          frontend:properties: [mode]
          frontend:references: [wicket.model, model.compareTo, engine, validator.id]
          frontend:services: [wicket.id, validator.id]
          type: exdocpickerbasedemo:newsdocument
          /root:
            jcr:primaryType: frontend:plugin
            extension.left: ${cluster.id}.left
            extension.right: ${cluster.id}.right
            plugin.class: org.hippoecm.frontend.editor.layout.TwoColumn
            wicket.extensions: [extension.left, extension.right]
          /left:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.left.item
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
            wicket.id: ${cluster.id}.left
          /right:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.right.item
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
            wicket.id: ${cluster.id}.right
          /title:
            jcr:primaryType: frontend:plugin
            field: title
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /introduction:
            jcr:primaryType: frontend:plugin
            field: introduction
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /informantextdocselector:
            jcr:primaryType: frontend:plugin
            caption: Informant
            engine: ${engine}
            external.document.service.facade: org.onehippo.forge.exdocpicker.demo.jpa.field.SimpleJPQLExternalDocumentServiceFacade
            initial.search.enabled: true
            jpql.external.docs.field.name: exdocpickerbasedemo:informantids
            jpql.item.description.prop: description
            jpql.item.iconlink.prop: photo
            jpql.item.id.prop: id
            jpql.item.id.type.prop: long
            jpql.item.search.query: SELECT i FROM Informant i WHERE i.id = :id
            jpql.item.search.query.param: id
            jpql.item.title.prop: name
            jpql.persistence.unit: newsPU
            jpql.term.search.query: SELECT i FROM Informant i
            jpql.term.search.query.param: ''
            mode: ${mode}
            plugin.class: org.onehippo.forge.exdocpicker.impl.field.ExternalDocumentFieldSelectorPlugin
            selection.mode: multiple
            wicket.id: ${cluster.id}.left.item
            wicket.model: ${wicket.model}
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /content:
            jcr:primaryType: frontend:plugin
            field: content
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /introextdocselector:
            jcr:primaryType: frontend:plugin
            caption: Introductary External Document
            engine: ${engine}
            example.external.docs.field.name: exdocpickerbasedemo:introexdocid
            external.document.service.facade: org.onehippo.forge.exdocpicker.demo.field.ExampleExternalDocumentServiceFacade
            initial.search.enabled: true
            mode: ${mode}
            plugin.class: org.onehippo.forge.exdocpicker.impl.field.ExternalDocumentFieldSelectorPlugin
            selection.mode: single
            wicket.id: ${cluster.id}.left.item
            wicket.model: ${wicket.model}
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /relatedextdocselector:
            jcr:primaryType: frontend:plugin
            caption: Related External Documents
            engine: ${engine}
            example.external.docs.field.name: exdocpickerbasedemo:relatedexdocids
            external.document.service.facade: org.onehippo.forge.exdocpicker.demo.field.ExampleExternalDocumentServiceFacade
            mode: ${mode}
            plugin.class: org.onehippo.forge.exdocpicker.impl.field.ExternalDocumentFieldSelectorPlugin
            selection.mode: multiple
            wicket.id: ${cluster.id}.left.item
            wicket.model: ${wicket.model}
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /externaltaxonomyselector:
            jcr:primaryType: frontend:plugin
            caption: External Taxonomy
            engine: ${engine}
            example.external.cats.field.name: exdocpickerbasedemo:excategories
            external.document.service.facade: org.onehippo.forge.exdocpicker.demo.field.tree.ExampleExternalSubjectCategoryServiceFacade
            initial.tree.expand.depth: '1'
            mode: ${mode}
            plugin.class: org.onehippo.forge.exdocpicker.impl.field.tree.ExternalTreeItemFieldSelectorPlugin
            selection.mode: multiple
            wicket.id: ${cluster.id}.left.item
            wicket.model: ${wicket.model}
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /date:
            jcr:primaryType: frontend:plugin
            field: date
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.right.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /hiddendateupdater:
            jcr:primaryType: frontend:plugin
            caption: Hidden Date Updater
            engine: ${engine}
            external.document.service.facade: org.onehippo.forge.exdocpicker.demo.jpa.field.SimpleJPQLExternalDocumentServiceFacade
            mode: ${mode}
            plugin.class: org.onehippo.forge.exdocpicker.demo.field.DateUpdatingHiddenFieldPlugin
            wicket.id: ${cluster.id}.right.item
            wicket.model: ${wicket.model}
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /author:
            jcr:primaryType: frontend:plugin
            field: author
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.right.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /source:
            jcr:primaryType: frontend:plugin
            field: source
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.right.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /location:
            jcr:primaryType: frontend:plugin
            field: location
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.right.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /image:
            jcr:primaryType: frontend:plugin
            field: image
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.right.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
